name            : cupertino_tabbar
description     : A highly customisable and simple widget for having iOS 13 style tab bars.
version         : 1.0.0
author          : Ali Yigit Bireroglu <aliyigitbireroglu@gmail.com>
repository      : https://github.com/aliyigitbireroglu/flutter-cupertino-tabbar
homepage        : https://www.cosmossoftware.coffee

environment     :
  sdk: ">=2.2.2 <3.0.0"

dependencies    :
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter         :
